### ISSUE TITLE
Implement self-reference IP address in ChatEvent

### ISSUE THREAD

**Issue by carlbennett** [BNETDocs/Atlas#8]
> **islanti** (19 Oct 2020):
> Suggestion for Atlas: include actual IP address in SID_CHATEVENTs for any self-referring messages
> That way bot can learn it's external IP

[![image](https://user-images.githubusercontent.com/592196/96846888-193b0100-1418-11eb-8af1-040d496babf6.png)](https://discord.com/channels/405789880749260820/502159267034431499/767909769293463582)

**Comment by OneMeanDragon** [comment]
if your going to do that you may as well implement the entirety of the 0xf in its original state, use account number as their connection id what not

**Comment by carlbennett** [comment]
Implemented.

Diff: https://github.com/BNETDocs/Atlas/compare/ab972f0ab8f184d0a22a7e83661d32a99d2dcbf0%5E...7bfe2e4cf5ee9e87eafab574df284b84f537bde8
